"""Static HTML dashboard snapshot generator.

This produces a self-contained HTML file (no external assets, theme-aware)
summarizing the current ranking. It is a point-in-time snapshot generated by
a run of the CLI/CI job — not a live-refreshing page, since no in-browser
data source is available for ATHEX quotes.
"""

from __future__ import annotations

import html
from datetime import datetime
from zoneinfo import ZoneInfo

from .scoring import Recommendation, VERDICT_AVOID, VERDICT_BUY, VERDICT_HOLD, VERDICT_STRONG_BUY

ATHENS_TZ = ZoneInfo("Europe/Athens")

_VERDICT_CLASS = {
    VERDICT_STRONG_BUY: "verdict-strong-buy",
    VERDICT_BUY: "verdict-buy",
    VERDICT_HOLD: "verdict-hold",
    VERDICT_AVOID: "verdict-avoid",
}

_PAGE_TEMPLATE = """<title>ΧΑΑ — Πρωινή Αναφορά</title>
<style>
:root {{
  --bg: #f7f7f8; --panel: #ffffff; --text: #1c1c1f; --muted: #6b6b76;
  --border: #e4e4e8; --buy: #1a7f37; --buy-bg: #e6f6ea;
  --hold: #9a6700; --hold-bg: #fff6e0; --avoid: #c62828; --avoid-bg: #fdecea;
  --accent: #2b59c3;
}}
@media (prefers-color-scheme: dark) {{
  :root:not([data-theme="light"]) {{
    --bg: #16171b; --panel: #1e2025; --text: #eaeaef; --muted: #9a9aa5;
    --border: #2c2e34; --buy: #4ade80; --buy-bg: #123a20;
    --hold: #facc15; --hold-bg: #3a2f0a; --avoid: #f87171; --avoid-bg: #3a1414;
    --accent: #7aa2ff;
  }}
}}
:root[data-theme="dark"] {{
  --bg: #16171b; --panel: #1e2025; --text: #eaeaef; --muted: #9a9aa5;
  --border: #2c2e34; --buy: #4ade80; --buy-bg: #123a20;
  --hold: #facc15; --hold-bg: #3a2f0a; --avoid: #f87171; --avoid-bg: #3a1414;
  --accent: #7aa2ff;
}}
* {{ box-sizing: border-box; }}
body {{
  background: var(--bg); color: var(--text); margin: 0; padding: 24px;
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
}}
.wrap {{ max-width: 960px; margin: 0 auto; }}
h1 {{ font-size: 1.4rem; margin-bottom: 4px; }}
.meta {{ color: var(--muted); font-size: 0.85rem; margin-bottom: 20px; }}
.disclaimer {{
  background: var(--panel); border: 1px solid var(--border); border-radius: 10px;
  padding: 14px 16px; font-size: 0.82rem; color: var(--muted); margin-bottom: 24px;
}}
.table-scroll {{ overflow-x: auto; border: 1px solid var(--border); border-radius: 12px; }}
table {{ width: 100%; border-collapse: collapse; background: var(--panel); font-size: 0.9rem; }}
th, td {{ padding: 10px 14px; text-align: left; border-bottom: 1px solid var(--border); white-space: nowrap; }}
th {{ color: var(--muted); font-weight: 600; font-size: 0.78rem; text-transform: uppercase; letter-spacing: 0.03em; }}
tr:last-child td {{ border-bottom: none; }}
.badge {{ display: inline-block; padding: 3px 10px; border-radius: 999px; font-size: 0.78rem; font-weight: 600; }}
.verdict-strong-buy, .verdict-buy {{ color: var(--buy); background: var(--buy-bg); }}
.verdict-hold {{ color: var(--hold); background: var(--hold-bg); }}
.verdict-avoid {{ color: var(--avoid); background: var(--avoid-bg); }}
.pos {{ color: var(--buy); }}
.neg {{ color: var(--avoid); }}
.score-bar-wrap {{ width: 90px; height: 6px; background: var(--border); border-radius: 4px; overflow: hidden; display: inline-block; vertical-align: middle; }}
.score-bar {{ height: 100%; background: var(--accent); }}
footer {{ margin-top: 20px; font-size: 0.78rem; color: var(--muted); }}
</style>
<div class="wrap">
  <h1>📈 ΧΑΑ — Αναφορά Αγοράς</h1>
  <div class="meta">Παράχθηκε: {generated_at} (ώρα Ελλάδας) · FTSE/Athex Large Cap</div>
  <div class="disclaimer">{disclaimer}</div>
  <div class="table-scroll">
    <table>
      <thead>
        <tr>
          <th>#</th><th>Μετοχή</th><th>Ticker</th><th>Τιμή</th><th>Μεταβολή</th>
          <th>RSI</th><th>Σκορ</th><th>Σήμα</th>
        </tr>
      </thead>
      <tbody>
        {rows}
      </tbody>
    </table>
  </div>
  <footer>Δεν αποτελεί επενδυτική συμβουλή. Δεδομένα με καθυστέρηση από Yahoo Finance.</footer>
</div>
"""

_ROW_TEMPLATE = """<tr>
  <td>{rank}</td>
  <td>{name}</td>
  <td><code>{symbol}</code></td>
  <td>{price:.2f}€</td>
  <td class="{change_class}">{change:+.2f}%</td>
  <td>{rsi}</td>
  <td>
    <span class="score-bar-wrap"><span class="score-bar" style="width:{score_width}%"></span></span>
    {score:+.0f}
  </td>
  <td><span class="badge {verdict_class}">{verdict}</span></td>
</tr>"""


def build_dashboard_html(recommendations: list[Recommendation], disclaimer: str) -> str:
    now = datetime.now(ATHENS_TZ)
    rows = []
    for i, rec in enumerate(recommendations, start=1):
        snap = rec.snapshot
        rsi_text = f"{snap.rsi14:.0f}" if snap.rsi14 is not None else "—"
        rows.append(
            _ROW_TEMPLATE.format(
                rank=i,
                name=html.escape(rec.name),
                symbol=html.escape(rec.symbol),
                price=snap.last_close,
                change=snap.change_pct,
                change_class="pos" if snap.change_pct >= 0 else "neg",
                rsi=rsi_text,
                score=rec.score,
                score_width=max(0, min(100, (rec.score + 100) / 2)),
                verdict_class=_VERDICT_CLASS.get(rec.verdict, ""),
                verdict=html.escape(rec.verdict),
            )
        )
    return _PAGE_TEMPLATE.format(
        generated_at=now.strftime("%A %d/%m/%Y %H:%M"),
        disclaimer=html.escape(disclaimer),
        rows="\n".join(rows),
    )
